### ISSUE TITLE
Use exceptions

### ISSUE THREAD

**Issue by MSadeghHE** [MSadeghHE/sleep-until#9]
Replace `exit()` function call with `throw` statement.

**Comment by ccsadegh** [comment]
After this change, the code size of compiled program is about 15% larger, that is worth it.

**Comment by MSadeghHE** [comment]
I am thinking again, and I should not use exceptions for this small utility which has a small file size. BTW calling `exit()` function directly in any place of the source code is not appropriate, and it should be replaced with a way of error codes.
